language: python
matrix:
  allow_failures:
  - python: '3.7'
  include:
  - python: '2.7'
    os: linux
  - python: '3.7'
    os: linux
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
    sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - python test/__init__.py
deploy:
  provider: pypi
  user: "qta"
  password:
    secure: "jPnIUdHointg7MLtEk2bbR5dcmygW/5FULbfMCrEPikz9D6+BOZkLNJ2DE3lih22DSe8/k6FXSpz6m7r6PWYoUB4edU2QLl0auZpJjKsBvnGD/a2oHyvJV5MKOQUtAOUDA0lM4hlyqs5Ece06SF+zsfbFQnIkmMos8MY9T2QlMBiB9K3IaZTcJtxWx4T+Yw3tbR8w2eZvYxJ4YNQ69u+N7PJAB9v8Tf4NenFWPZe+gqTEx1XVIb07Mj9pno0jvS5RLGILV7jmCaM3nUx1gPITwT1bd1ArA2wTgNdXzRpRHOYptnItIcd+1GxS+SrqerS+HrrBGA+XlCKcBrjX/tCYmSQjpA4NykpNwXR/Q2PNH4FGltAkhdQiMBycMBv+SZzcqdfv2olu+1+HhXvfVW7iq4hlhvSmF/zLYax9Op0i25qm3VIrBdEJh795iV8S2Ty1Kim9DLmtGjtlQh9h4qFgnEmReWUbD+fVBZKsif+RixFe90Ik8RmpBqIsKn6Jd+tDj0igNYQ/tnekmL0JQdoCbh1V2Dqykh8MZ76K3GaG3adxCtLQTCqb15RzCkj/gm7lyeYreaQ7pf1dqvU1VlqpynQU5XZq6FF4IqeSFERAND9SEsKjc9Rp0Z2WzdLS5OqFJwVbfieSvhR2wxKH0uV5IlJlU7Y91us1GwnMmxac20="
  on:
    tags: true
